.TH 9WEATHER 1
.SH NAME
9weather \- weather forecast
.SH SYNOPSIS
.B 9weather
[
.I -d seconds
]
[
.I -i
]
[
.I -z zip,country
]
[
.I -k apikey
]
.SH DESCRIPTION
.I 9weather
retrieves weather data from OpenWeatherMap and requires an API key for
access.  You can easily obtain a free API key by registering at
http://openweathermap.org/
.PP
By default, 9weather fetches weather data every 5 minutes. This interval
can be changed by setting the
.I \-d
flag, followed by the desired delay in seconds.
.PP
9weather normally displays the temperature in metric units, to display
in imperial units add the
.I \-i
flag.
.PP
9weather obtains the API key by default from
.IR factotum (4).
You can add an entry like:
.RS
key proto=pass service=9weather user=openweathermap !password=my_api_key
.RE
If factotum does not contain the key, 9weather will try to read it from
the environment variable
.B openweathermap.
You can also manually specify the API key using the
.I \-k
flag.
.PP
The geolocation ZIP code is obtained from the environment variable
.B ZIP
by default. You can manually specify a ZIP code using the
.I \-z
flag.
.EE
.SH EXAMPLES
.EX
9weather -z Shanghai -k my_api_key
.EE
.SH BUGS
Probably.
