.TH 9WEATHER 1
.SH NAME
9weather \- weather forecast
.SH SYNOPSIS
.B 9weather
[
.I -d seconds
]
[
.I -i
]
[
.I -z zip,country
]
[
.I -k apikey
]
.SH DESCRIPTION
.I 9weather
makes requests to OpenWeatherMap and such, requires a API key
in order to be used. You can register and get a free key at
http://openweathermap.org.
.PP
The default delay between each pull is 5 minutes, this can be
changed by setting the
.I \-d
flag.
.PP
In order to display the temperature using imperial units add the
.I \-i
flag.
.PP
9weather reads the environment variables
.B openweathermap
and
.B ZIP
to determine the API key and geolocation, they both can be overwritten
with the -z and -k flag respectively.
.EE
.SH EXAMPLES
.EX
9weather -z Stockholm -k my_api_key
.EE
.SH SEE ALSO
.EX
weather(1)
.EE
.SH BUGS
Probably.
